/*
 * TechTrain MISSION Game API
 *
 * TechTrain MISSION ゲームAPI入門仕様  まずはこのAPI仕様に沿って機能を実装してみましょう。    この画面の各APIの「Try it out」->「Execute」を利用することで  ローカル環境で起動中のAPIにAPIリクエストをすることができます。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
	"net/http"
	"techtrain-mission/go/db"
	"techtrain-mission/go/helper"
)

// CharacterListGet - ユーザ所持キャラクター一覧取得API
func CharacterListGet(c *gin.Context) {
	token := c.GetHeader("X-Token")
	userID, err := helper.GetUserIDFromToken(token)
	if err != nil {
		_ = c.AbortWithError(http.StatusUnauthorized, err).SetType(gin.ErrorTypePrivate)
		return
	}

	// TODO: 簡潔にできる?
	query := "select UserCharacter.ID as UserCharacterID, " +
		"`Character`.ID as CharacterID, " +
		"`Character`.Name as Name " +
		"from UserCharacter " +
		"inner join `Character` on UserCharacter.CharacterID = `Character`.ID " +
		"where UserCharacter.UserID = ?;"

	var characters []UserCharacter
	_, err = db.GetDB().Select(&characters, query, userID)
	if err != nil {
		_ = c.AbortWithError(http.StatusInternalServerError, err).SetType(gin.ErrorTypePrivate)
		return
	}

	c.JSON(http.StatusOK, CharacterListResponse{Characters: characters})
}
