/*
 * TechTrain MISSION Game API
 *
 * TechTrain MISSION ゲームAPI入門仕様  まずはこのAPI仕様に沿って機能を実装してみましょう。    この画面の各APIの「Try it out」->「Execute」を利用することで  ローカル環境で起動中のAPIにAPIリクエストをすることができます。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// UserCreatePost - ユーザ情報作成API
func UserCreatePost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UserGetGet - ユーザ情報取得API
func UserGetGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UserUpdatePut - ユーザ情報更新API
func UserUpdatePut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
